apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-agent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-agent
    app.kubernetes.io/part-of: kserve-agent
  name: kserve-agent
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-agent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-agent
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-agent/kserve-agent@sha256:e881d78cc8d9d2b2de41c01c153c62768c168f8228814f62d8d0c431aa9eb5e3
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
